let
    Fonte = Excel.Workbook(File.Contents("C:\Users\kauan\Downloads\base_vendas_suja.xlsx"), null, true),
    Sheet1_Sheet = Fonte{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data_Venda", type date}, {"Produto", type text}, {"Categoria", type text}, {"Cliente_Nome", type text}, {"Email_Cliente", type text}, {"Telefone", type text}, {"Região", type text}, {"Vendedor", type text}, {"Quantidade", type any}, {"Preço_Unitário", type number}, {"Valor_Total", type number}, {"Forma_Pagamento", type text}, {"Desconto", type text}, {"Status_Entrega", type text}, {"Observações", type text}}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Telefone", "Email_Cliente"}),
    #"Valor Substituído2" = Table.ReplaceValue(#"Colunas Removidas",null,"0",Replacer.ReplaceValue,{"Desconto"}),
    #"Valor Substituído" = Table.ReplaceValue(#"Valor Substituído2","três",3,Replacer.ReplaceValue,{"Quantidade"}),
    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","dois",2,Replacer.ReplaceValue,{"Quantidade"}),
    #"Divisão Inserida" = Table.AddColumn(#"Valor Substituído1", "Divisão", each [Valor_Total] / [Quantidade], type number),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Divisão Inserida",{"Data_Venda", "Produto", "Categoria", "Cliente_Nome", "Região", "Vendedor", "Quantidade", "Preço_Unitário", "Divisão", "Valor_Total", "Forma_Pagamento", "Desconto", "Status_Entrega", "Observações"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Reordenadas",{{"Divisão", Currency.Type}}),
    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado1",{"Preço_Unitário"}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas1",{{"Divisão", "Preco Unitário"}}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Valor_Total", Currency.Type}, {"Quantidade", Int64.Type}}),
    #"Valor Substituído3" = Table.ReplaceValue(#"Tipo Alterado2","roupa","Roupas",Replacer.ReplaceText,{"Categoria"}),
    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3","acessorio","Acessórios",Replacer.ReplaceText,{"Categoria"}),
    #"Valor Substituído5" = Table.ReplaceValue(#"Valor Substituído4","Calçado","Calçados",Replacer.ReplaceText,{"Categoria"}),
    #"Valor Substituído6" = Table.ReplaceValue(#"Valor Substituído5","Calçadoss","Calçados",Replacer.ReplaceText,{"Categoria"}),
    #"Valor Substituído7" = Table.ReplaceValue(#"Valor Substituído6","Boné Preto","Boné Preto (P)",Replacer.ReplaceValue,{"Produto"}),
    #"Valor Substituído8" = Table.ReplaceValue(#"Valor Substituído7","Boné Preto azul","Boné Preto",Replacer.ReplaceText,{"Produto"}),
    #"Valor Substituído9" = Table.ReplaceValue(#"Valor Substituído8","Calça Jeans","Calça Jeans (P)",Replacer.ReplaceValue,{"Produto"}),
    #"Valor Substituído10" = Table.ReplaceValue(#"Valor Substituído9","Calça Jeans azul","Calça Jeans Azul",Replacer.ReplaceText,{"Produto"}),
    #"Valor Substituído12" = Table.ReplaceValue(#"Valor Substituído10","Camiseta Azul azul","Camiseta Azul",Replacer.ReplaceText,{"Produto"}),
    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Valor Substituído12", "Produto", Splitter.SplitTextByDelimiter("(", QuoteStyle.Csv), {"Produto.1", "Produto.2"}),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Produto.1", type text}, {"Produto.2", type text}}),
    #"Valor Substituído11" = Table.ReplaceValue(#"Tipo Alterado3",")","",Replacer.ReplaceText,{"Produto.2"}),
    #"Valor Substituído13" = Table.ReplaceValue(#"Valor Substituído11",null,"Não informado",Replacer.ReplaceValue,{"Produto.2"}),
    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Valor Substituído13",{{"Produto.2", type text}}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Tipo Alterado5",{{"Produto.2", "Tamanhos"}}),
    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas1", "Personalizar", each if Text.Contains([Produto.1], "Tênis") then "Calçados" else if Text.Contains([Produto.1], "Boné") then "Acessórios" else if Text.Contains([Produto.1], "Camiseta") then "Roupas" else if Text.Contains([Produto.1], "Calça") then "Roupas" else if Text.Contains([Produto.1], "Mochila") then "Acessórios" else null),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Coluna Condicional Adicionada",{"Data_Venda", "Produto.1", "Tamanhos", "Personalizar", "Categoria", "Cliente_Nome", "Região", "Vendedor", "Quantidade", "Preco Unitário", "Valor_Total", "Forma_Pagamento", "Desconto", "Status_Entrega", "Observações"}),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Reordenadas1",{"Categoria"}),
    #"Colunas Renomeadas2" = Table.RenameColumns(#"Colunas Removidas2",{{"Personalizar", "Categoria"}}),
    #"Valor Substituído14" = Table.ReplaceValue(#"Colunas Renomeadas2","Paraná","Sul",Replacer.ReplaceText,{"Região"}),
    #"Valor Substituído15" = Table.ReplaceValue(#"Valor Substituído14","SP","Sudeste",Replacer.ReplaceText,{"Região"}),
    #"Valor Substituído16" = Table.ReplaceValue(#"Valor Substituído15","PR","Sul",Replacer.ReplaceText,{"Região"}),
    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Valor Substituído16",{{"Vendedor", Text.Proper, type text}}),
    #"Colunas Removidas3" = Table.RemoveColumns(#"Colocar Cada Palavra Em Maiúscula",{"Cliente_Nome"}),
    #"Texto em Maiúscula" = Table.TransformColumns(#"Colunas Removidas3",{{"Forma_Pagamento", Text.Upper, type text}}),
    #"Valor Substituído17" = Table.ReplaceValue(#"Texto em Maiúscula","CARTAO","CARTÃO",Replacer.ReplaceText,{"Forma_Pagamento"}),
    #"Valor Substituído18" = Table.ReplaceValue(#"Valor Substituído17","",null,Replacer.ReplaceValue,{"Tamanhos"}),
    #"Valor Substituído19" = Table.ReplaceValue(#"Valor Substituído18",".",",",Replacer.ReplaceText,{"Desconto"}),
    #"Valor Substituído20" = Table.ReplaceValue(#"Valor Substituído19","dez","0,1",Replacer.ReplaceText,{"Desconto"}),
    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Valor Substituído20",{{"Desconto", Percentage.Type}}),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Tipo Alterado4",{"Data_Venda", "Produto.1", "Tamanhos", "Categoria", "Região", "Vendedor", "Quantidade", "Preco Unitário", "Valor_Total", "Desconto", "Forma_Pagamento", "Status_Entrega", "Observações"}),
    #"Valor Substituído21" = Table.ReplaceValue(#"Colunas Reordenadas2","Pretocorrida","Preto Corrida",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído22" = Table.ReplaceValue(#"Valor Substituído21","Pretoescolar","Preto Escolar",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído23" = Table.ReplaceValue(#"Valor Substituído22","Jeanscorrida","Jeans Corrida",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído24" = Table.ReplaceValue(#"Valor Substituído23","Jeansescolar","Jeans Escolar",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído25" = Table.ReplaceValue(#"Valor Substituído24","Camiseta Azul ","Camiseta Azul",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído26" = Table.ReplaceValue(#"Valor Substituído25","Camiseta AzulAzul","Camiseta Azul",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído27" = Table.ReplaceValue(#"Valor Substituído26","Azulescolar","Azul Escolar",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído28" = Table.ReplaceValue(#"Valor Substituído27","Azulcorrida","Azul Corrida",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído29" = Table.ReplaceValue(#"Valor Substituído28","Escolar ","Escolar",Replacer.ReplaceText,{"Produto.1"}),
    #"Linhas Filtradas" = Table.SelectRows(#"Valor Substituído29", each true),
    #"Valor Substituído30" = Table.ReplaceValue(#"Linhas Filtradas","Boné Preto ","Boné Preto",Replacer.ReplaceValue,{"Produto.1"}),
    #"Linhas Filtradas1" = Table.SelectRows(#"Valor Substituído30", each true),
    #"Valor Substituído31" = Table.ReplaceValue(#"Linhas Filtradas1","EscolarAzul","Escolar Azul",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído32" = Table.ReplaceValue(#"Valor Substituído31","Escolarcorrida","Escolar Corrida",Replacer.ReplaceText,{"Produto.1"}),
    #"Linhas Filtradas2" = Table.SelectRows(#"Valor Substituído32", each true),
    #"Valor Substituído33" = Table.ReplaceValue(#"Linhas Filtradas2","Escolarescolar","Escolar",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído34" = Table.ReplaceValue(#"Valor Substituído33","Corrida azul","Corrida Azul",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído35" = Table.ReplaceValue(#"Valor Substituído34","Tênis Corridacorrida","Tênis Corrida",Replacer.ReplaceValue,{"Produto.1"}),
    #"Valor Substituído36" = Table.ReplaceValue(#"Valor Substituído35","Tênis Corrida ","Tênis Corrida",Replacer.ReplaceValue,{"Produto.1"}),
    #"Valor Substituído37" = Table.ReplaceValue(#"Valor Substituído36","Corridaescolar","Corrida Escolar",Replacer.ReplaceText,{"Produto.1"}),
    #"Valor Substituído38" = Table.ReplaceValue(#"Valor Substituído37",null,"Não Informado",Replacer.ReplaceValue,{"Região"}),
    #"Tipo Alterado6" = Table.TransformColumnTypes(#"Valor Substituído38",{{"Categoria", type text}}),
    #"Valor Substituído39" = Table.ReplaceValue(#"Tipo Alterado6",null,"Não Informado",Replacer.ReplaceValue,{"Status_Entrega"}),
    #"Valor Substituído40" = Table.ReplaceValue(#"Valor Substituído39","---","Não Informado",Replacer.ReplaceText,{"Observações"}),
    #"Valor Substituído41" = Table.ReplaceValue(#"Valor Substituído40",null,"Não Informado",Replacer.ReplaceValue,{"Observações"}),
    #"Multiplicação Inserida" = Table.AddColumn(#"Valor Substituído41", "Multiplicação", each [Valor_Total] * [Desconto], Currency.Type),
    #"Colunas Renomeadas3" = Table.RenameColumns(#"Multiplicação Inserida",{{"Multiplicação", "Valor_Desconto_Reais"}, {"Preco Unitário", "Preco_Unitário"}, {"Produto.1", "Produto"}}),
    #"Colunas Reordenadas3" = Table.ReorderColumns(#"Colunas Renomeadas3",{"Data_Venda", "Produto", "Tamanhos", "Categoria", "Região", "Vendedor", "Quantidade", "Preco_Unitário", "Valor_Total", "Desconto", "Valor_Desconto_Reais", "Forma_Pagamento", "Status_Entrega", "Observações"}),
    #"Subtração Inserida" = Table.AddColumn(#"Colunas Reordenadas3", "Subtração", each [Valor_Total] - [Valor_Desconto_Reais], Currency.Type),
    #"Colunas Renomeadas4" = Table.RenameColumns(#"Subtração Inserida",{{"Subtração", "Valor_Pago"}}),
    #"Colunas Reordenadas4" = Table.ReorderColumns(#"Colunas Renomeadas4",{"Data_Venda", "Produto", "Tamanhos", "Categoria", "Região", "Vendedor", "Quantidade", "Preco_Unitário", "Valor_Total", "Desconto", "Valor_Desconto_Reais", "Valor_Pago", "Forma_Pagamento", "Status_Entrega", "Observações"})
in
    #"Colunas Reordenadas4"
